import { CountryConfig, CountryCode } from './types';
export { usaConfig } from './usa';
export { koreaConfig } from './korea';
export { schengenConfig } from './schengen';
export { canadaConfig } from './canada';
export { japanConfig } from './japan';
export { irelandConfig } from './ireland';
export { ukConfig } from './uk';
export { australiaConfig } from './australia';
export { newZealandConfig } from './new-zealand';
export * from './types';
export declare const countryConfigs: Record<CountryCode, CountryConfig>;
export declare const getCountryConfig: (code: CountryCode) => CountryConfig;
export declare const getAvailableCountries: () => CountryConfig[];
export declare const findCountryByCode: (code: string) => CountryConfig | undefined;
export declare const countryList: {
    code: string;
    name: string;
    flag: string;
}[];
export declare const DEFAULT_COUNTRY: CountryCode;
